### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MajidHeydari** [neo4j-contrib/django-neomodel#51] opened 2021-03-04 13:54 UTC
http://127.0.0.1:8000/admin/
I went to go to address error and I did it according to the document but the code was not done.
settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by whatSocks** [comment] 2021-07-06 14:40
duplicate of https://github.com/neo4j-contrib/django-neomodel/issues/60

**Closed by whatSocks** 2021-07-06 14:40 UTC
